### PR TITLE
Apply example_ynh

### LINKED ISSUE #26: [Buster] Adapt the PHP 7.x custom install / requirement
c.f. https://ci-buster.nohost.me/ci/job/416

Following the discussion started [here](https://github.com/YunoHost/issues/issues/1255#issuecomment-596254890), this app needs to be adapted both to : 
- be installable on a fresh Buster system
- make the transition smooth for people upgrading from Stretch to Buster

Currently the app relies on a custom install of PHP 7.1 / 7.2 / 7.3 which should be adapted. Imho (to be discussed and see with other app packagers after we gain more XP with this) : 
- the scripts should be adapted to use PHP 7.3 instead of 7.2
- the upgrade script should take care of the move from 7.2 to 7.3 (which for users could and should therefore happen prior to the upgrade to buster)
- we should have an if/else to install PHP 7.3 only if we're on stretch (and not on buster) [similar to what's done for pixelfed for example](https://github.com/YunoHost-Apps/pixelfed_ynh/pull/102)

### PR DESCRIPTION
**Pull request by yalh76**
Apply example_ynh

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/pilea_ynh%20PR30%20(yalh76)/)

### CODE REVIEW

**Comment by SimonMellerin** [comment]
Waw, thanks for your work here ! 

I've not so much time to adapt this package for buster and with the new way PHP version should be handled. I really appreciate, thanks 

Don't hesitate if you have any question on pilea specific part

**Comment by SimonMellerin** [comment]
Have you seen what I have started to do in #27 ? 

Did you take care about the Debian stretch retrocompatibility ?

**Comment by SimonMellerin** [comment]
Ah ! This new way to deal with PHP version appeared with Yunohost 3.8 ! Nice

**Comment by yalh76** [comment]
> 
> 
> Have you seen what I have started to do in #27 ?
> 
> Did you take care about the Debian stretch retrocompatibility ?

Yes I've seen #27, it was what we have to do before 3.8.1 and `ynh_add_fpm_config  `implementing `--package=packages` https://github.com/YunoHost/yunohost/blob/stretch-stable/data/helpers.d/php#L61 

and yes it cares of stretch.
On stretch it installs PHP7.3 and the required packages
On Buster it only install required packages
It's included in the new version of the helper

**Comment by yalh76** [comment]
I just don't undertsand why `ynh_setup_source "$TMPDIR"` is made to a tempdir instead of the `$final_path` as usual

**Comment by SimonMellerin** [comment]
> I just don't understand why `ynh_setup_source "$TMPDIR"` is made to a tempdir instead of the `$final_path` as usual

Well... when I started this package, I didn't really know exactly Yunohost and what I was doing. As Wallabag is a Symfony app and it was well integrated to Yunohost, I copied Wallabag package and adapted it to Pilea.
So I don't know exactly why I used this `$TMPDIR`, may be it was a good practice at this time ?

You know yunohost packaging better than me, if the good practice is to directly use `$final_path` then we should use `$final_path` here

**Comment by yalh76** [comment]
Well, it seems that now, wallabag2 do `ynh_setup_source --dest_dir="$final_path"` https://github.com/YunoHost-Apps/wallabag2_ynh/blob/9f9d4fe3be0d6aeb48675552cda7b3368fdf9d75/scripts/install#L76

Usually putting sources to a tempdir is when you need to build the app and then just retrieve the built without the sources.

I will change the PR :)

**Review by SimonMellerin — APPROVED** [review]
Seems good to me, thanks again for your work !

**Pull request merged**
